#
# This is the main global crabgrass configuration. 
# 
# Most of the time, no other configuration should be required other than the
# options in this file. Unusual options might be configured elsewhere.
#
# For true/false and numeric values, you must not enclose the value in quotes.
#
# See doc/CONFIGURATION for more details.
#

title: "Crabgrass Development"
enabled_mods:
  - super_admin
email:
  delivery_method: :sendmail
sites:
  - name: site1
    admin_group: superadmins
  - name: site2
    admin_group: superadmins

