#
# This is the main global crabgrass configuration. 
# 
# Most of the time, no other configuration should be required other than the
# options in this file. Unusual options might be configured elsewhere.
#
# For true/false and numeric values, you must not enclose the value in quotes.
#
# See doc/CONFIGURATION for more details.
#

##
## GLOBAL
##

enabled_languages:
  - en_US
  - es_ES
  - pt_BR
  - ar_EG
  - fr_FR
enabled_mods:
  - super_admin
  - student
  - connectingclassrooms
enabled_tools:
  - asset_tool
  - core_tools
  - event_tool
  - ranked_vote_tool
  - rate_many_tool
  - task_list_tool
  - wiki_tool
  - survey_tool
  - gallery_tool
  - external_video_tool
  - announcement_tool
  - feed_tool
  - survey_tool
email:
  delivery_method: :sendmail

profiles:
  - private
profile_fields:
  - basic
  - notes
  - websites

##
## SITES
##

sites:
  - name: connectingclassrooms
    admin_group: superadmin

##
## SITE DEFAULTS
##

pagination_size: 30
default_language: en_US
enforce_ssl: false
show_exceptions: true
email_sender: "robot@$current_host"
chat: false
tracking: true
require_user_email: true
available_page_types:
  - WikiPage
  - AssetPage
  - ExternalVideoPage
  - TaskListPage
  - AnnouncementPage
  - SurveyPage
  - DiscussionPage
  - RateManyPage
  - RankedVotePage
  - ArticlePage
  - Gallery
  - WikiPage

