#
# This is the main global crabgrass configuration. 
# 
# Most of the time, no other configuration should be required other than the
# options in this file. Unusual options might be configured elsewhere.
#
# For true/false and numeric values, you must not enclose the value in quotes.
#
# See doc/CONFIGURATION for more details.
#

##
## GLOBAL
##

enabled_languages:
  - en_US
  - es_ES
  - pt_BR
  - ar_EG
  - fr_FR
  - ru_RU
enabled_mods:
  - super_admin
enabled_tools:
  - asset_tool
  - core_tools
  - event_tool
  - ranked_vote_tool
  - rate_many_tool
  - task_list_tool
  - wiki_tool
  - survey_tool
  - gallery_tool
  - external_video_tool
  - announcement_tool
  - survey_tool
email:
  delivery_method: :sendmail

##
## SITES
##

sites:
  - name: climatechange
    admin_group: superadmin
  - name: globalpulse
    admin_group: superadmin
  - name: speakafrica
    admin_group: superadmin
  - name: iaids
    admin_group: superadmin
  - name: j8summit
    admin_group: superadmin
  - name: factsforlife
    admin_group: superadmin

##
## SITE DEFAULTS
##

title: umbrella
pagination_size: 30
default_language: en_US
enforce_ssl: false
show_exceptions: false
email_sender: "crabgrass-system@$current_host"
tracking: true
require_user_email: true
available_page_types:
  - WikiPage
  - AssetPage
  - ExternalVideoPage
  - TaskListPage
  - SurveyPage
  - DiscussionPage
  - RateManyPage
  - MessagePage
  - RankedVotePage
  - ArticlePage
  - Gallery
  - WikiPage

