#
# This is the main global crabgrass configuration.
#
# Most of the time, no other configuration should be required other than the
# options in this file. Unusual options might be configured elsewhere.
#
# For true/false and numeric values, you must not enclose the value in quotes.
#
# See doc/CONFIGURATION for more details.
#

##
## GLOBAL
##

enabled_languages:
  - en
  - es
  - pt
  - ar
  - fr
  - ru
  - tr
enabled_mods:
  - super_admin
  - moderation
  - evil_mod
enabled_tools:
  - asset_tool
  - core_tools
  - event_tool
  - ranked_vote_tool
  - rate_many_tool
  - task_list_tool
  - wiki_tool
  - survey_tool
  - gallery_tool
  - external_video_tool
  - announcement_tool
  - survey_tool
email:
  delivery_method: :sendmail
dev_email: "jeffrey@tinflag.com"

profiles:
  - private
profile_fields:
  - basic
  - notes
  - websites

# ensure_page_owner: false

text_editor: greencloth_only

require_user_full_info: true
##
## SITES
##

sites:
  - name: climatechange
    moderation_group: siteadminclimate
    admin_group: siteadminclimate
  - name: globalpulse
    admin_group: siteadminpulse
    moderation_group: siteadminpulse
  - name: speakafrica
    admin_group: siteadminspeak
    moderation_group: siteadminspeak
  - name: iaids
    admin_group: siteadminiaids
    moderation_group: siteadminiaids
  - name: j8summit
    admin_group: siteadminj8
    moderation_group: siteadminj8
    signup_mode: 2 # that is invite_only
  - name: voiceofyouth
    admin_group: siteadminvoy
    moderation_group: siteadminvoy

##
## SITE DEFAULTS
##

title: umbrella
pagination_size: 30
default_language: en
enforce_ssl: false
chat: false
show_exceptions: false
email_sender: "crabgrass-system@$current_host"
tracking: true
require_user_email: true
available_page_types:
  - ArticlePage
  - AssetPage
  - DiscussionPage
  - ExternalVideoPage
  - Gallery
  - MessagePage
  - RankedVotePage
  - RateManyPage
  - SurveyPage
  - TaskListPage
  - WikiPage

