#
# This is the main global crabgrass configuration.
#
# Most of the time, no other configuration should be required other than the
# options in this file. Unusual options might be configured elsewhere.
#
# For true/false and numeric values, you must not enclose the value in quotes.
#
# See doc/CONFIGURATION for more details.
#

#
# development tips:
#
#  * to work with super_admin, enable super_admin mod and site 'site1'.
#

title: "Crabgrass Development"

enabled_languages:
  - en
  - es
  - pt
  - ar
  - fr
enabled_mods:
#  - super_admin
#  - student
#  - connectingclassrooms
#  - moderation
  - no_private_messages
  - enhanced_stats
  - soundcloud
  - openlayers
  # - ui_tester
  # - design_tester
  # - translator

email:
  delivery_method: :sendmail

profiles:
  - private
profile_fields:
  - basic
  - notes
  - websites
all_profiles_visible: 1

text_editor: greencloth_only

profiles:
  - private
profile_fields:
  - basic
  - notes
  - websites
all_profiles_visible: 1

#use_full_geonames_data: true

##
## SITES
##

sites:
  - name: site1
    admin_group: rainbow
    moderation_group: rainbow
    evil:
       soundcloud:
         client_id: eee3f3174759328707c73a0be2652fce
         client_secret: bce994a5f79e241cbe94e4035e4a224b
         refresh_token: 00d9758035332c1081b67419eee74632
         enabled: true

# bound to test.host
#  - name: site2
#    admin_group: superadmins


available_page_types:
  - AssetPage
  #- EventPage
  - ExternalVideoPage
  - TaskListPage
  - AnnouncementPage
  - SurveyPage
  - DiscussionPage
  - RateManyPage
  #- MessagePage
  - RankedVotePage
  - ArticlePage
  - Gallery
  - WikiPage
