#
# This is the main global crabgrass configuration.
#
# Most of the time, no other configuration should be required other than the
# options in this file. Unusual options might be configured elsewhere.
#
# For true/false and numeric values, you must not enclose the value in quotes.
#
# See doc/CONFIGURATION for more details.
#

##
## GLOBAL
##

enabled_languages:
  - en_US
  - es_ES
  - pt_BR
  - ar_EG
  - tr_TR
enabled_mods:
enabled_tools:
  - asset_tool
  - core_tools
  - ranked_vote_tool
  - rate_many_tool
  - task_list_tool
  - wiki_tool
  - survey_tool
  - gallery_tool
  - external_video_tool
  - announcement_tool
email:
  delivery_method: :sendmail
  dev_email: "jeffrey@tinflag.com"
ensure_page_owner: false

##
## SITES
##

sites:
  - name: share
    admin_group: admins
  - name: facts
    admin_group: admins

##
## SITE DEFAULTS
##

pagination_size: 30
enforce_ssl: false
show_exceptions: false
email_sender: "robot@$current_host"
tracking: true
available_page_types:
  - AssetPage
  - ExternalVideoPage
  - TaskListPage
  - DiscussionPage
  - RateManyPage
  - MessagePage
  - RankedVotePage
  - ArticlePage
  - Gallery
  - WikiPage
  - SurveyPage

