--- 
- !ruby/object:PageClassProxy 
  class_description: A group discussion on a particular topic.
  class_display_name: group discussion
  class_group: discussion
  class_name: Discussion
  controller: discussion
  full_class_name: Tool::Discussion
  icon: discussion.png
- !ruby/object:PageClassProxy 
  class_description: Approve or disapprove of each possibility.
  class_display_name: approval vote
  class_group: poll
  class_name: RateMany
  controller: rate_many
  full_class_name: Tool::RateMany
  icon: rate-many.png
  model: Poll
- !ruby/object:PageClassProxy 
  class_description: an uploaded file
  class_display_name: file
  class_group: asset
  class_name: Asset
  controller: asset
  full_class_name: Tool::Asset
  icon: package.png
  model: Asset
- !ruby/object:PageClassProxy 
  class_description: A free-form text document.
  class_display_name: wiki
  class_group: wiki
  class_name: TextDoc
  controller: wiki
  full_class_name: Tool::TextDoc
  icon: wiki.png
  model: Wiki
- !ruby/object:PageClassProxy 
  class_description: 
  class_display_name: 
  class_group: request
  class_name: Request
  controller: request
  full_class_name: Tool::Request
  icon: bullhorn.png
  model: Poll
- !ruby/object:PageClassProxy 
  class_description: An event added to the personal/group/public calendar.
  class_display_name: event
  class_group: event
  class_name: Event
  controller: event
  full_class_name: Tool::Event
  icon: date.png
- !ruby/object:PageClassProxy 
  class_description: A list of todo items.
  class_display_name: task list
  class_group: task
  class_name: TaskList
  controller: tasklist
  full_class_name: Tool::TaskList
  icon: task-list.png
  model: TaskList
- !ruby/object:PageClassProxy 
  class_description: A personal message sent to individual recipients.
  class_display_name: personal message
  class_group: message
  class_name: Message
  controller: message
  full_class_name: Tool::Message
  icon: message.png
- !ruby/object:PageClassProxy 
  class_description: 
  class_display_name: 
  class_group: 
  class_name: RequestDiscussion
  controller: request_discussion
  full_class_name: Tool::RequestDiscussion
  icon: 
- !ruby/object:PageClassProxy 
  class_description: Rank possibilities in order of preference.
  class_display_name: ranked vote
  class_group: vote
  class_name: RankedVote
  controller: ranked_vote
  full_class_name: Tool::RankedVote
  icon: ballot.png
  model: Poll
- !ruby/object:PageClassProxy 
  class_description: 
  class_display_name: 
  class_group: info
  class_name: Info
  controller: info
  full_class_name: Tool::Info
  icon: info.png
