default:
  name: crabgrass
  domain: localhost
  email_sender: 'crabgrass-system@localhost'
  pagination_size: 29
  super_admin_group_id: 35
  default_language:
  - en_US
  available_page_types:
  - Message
  - Discussion
  - Wiki
  - Article
  - RateMany
  - RankedVote
  - TaskList
  - Asset
  - Gallery
  - ExternalVideo
  evil:
    google_analytics:
      enabled: false
      site_id: UA-XXXXXX-X
      https: false
  tracking: false

