globalpulse:
  name: globalpulse
  domain: global-pulse.org
  email_sender: 'crabgrass-system@global-pulse.org'
  secret: 'd54833cab5fafc217f2c552f7663c0524a938efed6df2af8bf134d3954fc8ac3214ca8c7'
  pagination_size: 29
  super_admin_group_id: 35
  default_language:
  - en_US
  available_page_types:
  - Message
  - Discussion
  - Wiki
  - Article
  - RateMany
  - RankedVote
  - TaskList
  - Asset
  - Gallery
  - ExternalVideo
  evil:
    google_analytics:
      enabled: false
      site_id: UA-XXXXXX-X
      https: false
  tracking: false
  network_id: 1

climatechange:
  name: climatechange
  domain: my.unite4climate.org
  email_sender: 'crabgrass-system@my.unite4climate.org'
  secret: 'd54833cab5fafc217f2c552f7663c0524a938efed6df2af8bf134d3954fc8ac3214ca8c7'
  pagination_size: 29
  super_admin_group_id: 35
  default_language:
  - en_US
  available_page_types:
  - Message
  - Discussion
  - Wiki
  - Article
  - RateMany
  - RankedVote
  - TaskList
  - Asset
  - Gallery
  - ExternalVideo
  evil:
    google_analytics:
      enabled: false
      site_id: UA-XXXXXX-X
      https: false
  tracking: false
  network_id: 2
