default:
  name: UNICEF
  domain: localhost
  email_sender: 'crabgrass-system@localhost'
  secret: 'd24833cab5fafcd17f2c555f7663c0524a938e5ed6df2af8bf134d3959fc8ac3214fa8c7'
  pagination_size: 29
  available_page_types:
  - Message
  - Discussion
  - TaskList
  - Asset

