default:
  name: crabgrass
  domain: localhost
  email_sender: 'crabgrass-system@localhost'
  secret: 'd24833cab5fafcd17f2c555f7663c0524a938e5ed6df2af8bf134d3959fc8ac3214fa8c7'
  pagination_size: 29
  default_language:
  - en_US
  available_page_types:
  - Message
  - Discussion
  - Wiki
  - Article
  - RateMany
  - RankedVote
  - TaskList
  - Asset
  - Gallery
  - ExternalVideo

# PROFILE SETTINGS
# ----------------
# Basic Example:
#
#   profiles:
#     public:
#       visible_to: noone
#     private:
#       elements: []
#       visible_to: [peers, friends]
#
# This deactivates the public profile while the private profile is enabled, being
# visible to all peers and friends, however only showing the basic information.
#
# ELEMENTS
#
# The other elements can be enabled by adding them to the `elements' list.
#
# Example:
#   profiles:
#     public: [location, notes, email_addresses]
#
# The user now can enter his location, as well as multiple notes and email
# addresses in the public profile. If the singular form of an element is used,
# the user can only enter one value, with the plural form she can add as many as
# wanted.
#
# Currently the following fields are supported:
#  * email_address
#  * location
#  * note
#  * website
#  * phone_number
#  * crypt_key
#
# VISIBILITY
# 
# Profiles can be made visible to different groups being:
#  * noone (deactivated)
#  * everyone (everyone who visits the site)
#  * users (everyone who is logged in)
#  * peers (users that share a group with the person)
#  * friends (users being in the person's contact list)
#
# Obviously 'everyone' implies users, peers and friends, users implies peers and
# friends, however peers does not include friends, so that peers and friends
# may see different profiles of a person.
#
# You can specify either one, or multiple groups for the visible_by field.
#
# Example:
#
#   profiles:
#     public:
#       visible_to: users
#     private:
#       visible_to: [peers, friends]
#


profiles:
  general_info: false
  public:
    elements: [note, location]
    visible_to: users
  private:
    elements: []
    visible_to: noone
