development:
    # config file::      config/#{environment}.sphinx.conf
    # searchd log file:: log/searchd.log
    # query log file::   log/searchd.query.log
    # pid file::         log/searchd.#{environment}.pid
    # searchd files::    db/sphinx/#{environment}/
    # allow star::       false
  port::             3312
  address::          localhost
  
test:
  port:             3313
  address:          localhost
  
