# options -------------------------------------------
# config file::      config/#{environment}.sphinx.conf
# searchd log file:: log/searchd.log
# query log file::   log/searchd.query.log
# pid file::         log/searchd.#{environment}.pid
# searchd files::    db/sphinx/#{environment}/
# allow star::       false

development:
  port: 3312
  address: localhost
  morphology: stem_en
  
test:
  port: 3313
  address: localhost
  morphology: stem_en

production:
  port: 3312
  address: localhost
  morphology: stem_en

