    # config file::      config/#{environment}.sphinx.conf
    # searchd log file:: log/searchd.log
    # query log file::   log/searchd.query.log
    # pid file::         log/searchd.#{environment}.pid
    # searchd files::    db/sphinx/#{environment}/
    # port::             3312
    # allow star::       false
  address::          localhost
