TextBoxWidget:
  :columns:
    - 1
    - 2
  :settings:
    - :title
    - :text
  :width: 1
ImageTitleWidget:
  :columns:
    - 2
  :settings:
    - :title
    - :image
MapWidget:
  :columns:
    - 1
    - 2
  :settings:
    - :title
    - :kml
    - :custom_kml
    - :map_center_latitude
    - :map_center_longitude
IntroWidget:
  :columns:
    - 2
  :settings:
    - :title
    - :text
    - :display_title
NetworkingWidget:
  :columns:
    - 1
  :settings:
    - :title
PageListWidget:
  :columns:
    - 2
  :settings:
    - :title
    - :display_title
    - :featured
    - :recent_pages
    - :most_viewed
    - :most_active
    - :most_stars
ButtonWidget:
  :columns:
    - 1
  :settings:
    - :title
    - :link
    - :icon
  :available_icons:
    - 'archive'
    - 'attach'
    - 'chat'
    - 'color_wheel'
    - 'date'
    - 'group'
    - 'heart'
    - 'key'
    - 'lightbulb'
    - 'lightning'
    - 'magnifier'
    - 'network'
    - 'ok'
    - 'page_discussion'
    - 'page_gallery'
    - 'page_survey'
    - 'pencil'
    - 'plus'
    - 'profile'
    - 'rss'
    - 'star'
    - 'tag'
    - 'weather_sun'
    - 'week'
    - 'whistle'
    - 'world'
    - 'wrench'
MenuWidget:
  :columns:
    - 1
  :settings:
    - :title
    - :menu_root_id
TagCloudWidget:
  :columns:
    - 1
    - 2
  :settings:
    - :title
    - :limit
  :width: 1

